language: objective-c
os: osx
osx_image: xcode7.3

branches:
	only:
    - developing
    - master

xcworkspace: JRDB.xcworkspace
xcode_scheme: JRDBTests
# xcode_project:  # path to your xcodeproj folder
